---
# Dataset options
data:         [/home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/data/baxter_babbling_rarm_3.5hrs_Dec14_16/postprocessmotions_f,/home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/data/baxter_babbling_rarm_wfixjts_5hrs_Feb10_17/postprocessmotionshalf_f,/home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/singlejtdata/data2k/joint0/postprocessmotions_f, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/singlejtdata/data2k/joint1/postprocessmotions_f, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/singlejtdata/data2k/joint2/postprocessmotions_f, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/singlejtdata/data2k/joint3/postprocessmotions_f, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/singlejtdata/data2k/joint4/postprocessmotions_f, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/singlejtdata/data2k/joint5/postprocessmotions_f, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/singlejtdata/data2k/joint6/postprocessmotions_f]
batch-size:   32
num-workers:  8
train-per:    0.6
val-per:      0.15
img-scale:    1e-4
step-len:     2
seq-len:      1
ctrl-type:    actdiffvel

# Model options
no-batch-norm:      False
pre-conv:           False
nonlin:             prelu
se3-type:           se3aa
pred-pivot:         False
num-se3:            8
init-transse3-iden: True
local-delta-se3:    False
wide-model:         True

# Loss options
loss-wt:				1.0
loss-scale:       10000.0

# Training options
no-cuda:        False
use-pin-memory: False
epochs:         20
start-epoch:    0
train-ipe:      2000
val-ipe:        500
evaluate:       False
seed:           100

# Optimization options
optimization: adam
lr:           1e-4
momentum:     0
lr-decay:     0.1
decay-epochs: 30

# Display/Save options
disp-freq: 25
save-dir:  trained_nets/supervised/transnets/8se3_1seq_alldata
disp-err-per-mask: True
