---
# Model options
checkpoint:   trained_nets/e2c/nonlin/simdata/smallv3/goaldir/det_step2_seq5_conv_hs1024_goal1em2_none/model_best.pth.tar
num-configs:  10
data-key:     val

# Optimization options
optimization:    gn
max-iter:        200
gn-perturb:      1e-3
gn-lambda:       1e-3
alpha:           0.0
alpha-dir:       0.5
alpha-dir-decay: 0.9975
conv-threshold:  1e-2
ctrl-init:       zero

# Misc options
disp-iter: 10
no-cuda:   False
seed:      100
save-dir:  trained_nets/e2c/nonlin/simdata/smallv3/goaldir/ctrlres_hs1024_goaldir
