---
# Dataset options
#"1step": "trained_nets/e2c/nonlin/simdata/deterministic/def_step2_seq1/model_best.pth.tar","3step": "trained_nets/e2c/nonlin/simdata/deterministic/def_step2_seq3/model_best.pth.tar","5step": "trained_nets/e2c/nonlin/simdata/deterministic/def_step2_seq5/model_best.pth.tar","7step": "trained_nets/e2c/nonlin/simdata/deterministic/def_step2_seq7/model_best.pth.tar",
model-dict:   {"5step": "trained_nets/e2c/nonlin/simdata/deterministic_n/def_step2_seq5/model_best.pth.tar","3step_in_ns": "trained_nets/e2c/nonlin/simdata/deterministic_n/def_step2_seq3_instance_nostatic/model_best.pth.tar","5step_in_ns": "trained_nets/e2c/nonlin/simdata/deterministic_n/def_step2_seq5_instance_nostatic/model_best.pth.tar","3step_in_ns_hwt": "trained_nets/e2c/nonlin/simdata/deterministic_n/def_step2_seq3_instance_nostatic_trans10/model_best.pth.tar","5step_in_ns_hwt": "trained_nets/e2c/nonlin/simdata/deterministic_n/def_step2_seq5_instance_nostatic_trans10/model_best.pth.tar"}
batch-size:   16
num-examples: 100
seq-len:      25
data-key:     val
jt-mean-thresh: 1e-3
save-dir:     trained_nets/e2c/nonlin/simdata/deterministic/predvizres